- Example/Pods/Pods.xcodeproj/project.pbxproj
- Example/Pods/Pods.xcodeproj/project.xcworkspace/contents.xcworkspacedata
I'm currently using this library via Carthage for a iOS 8.0+ app, and the original settings prevents it :( 
Hope this pull request will help other users out there!
> Change JTAppleCalendar deployment target to 8.0 instead of 8.3

- Example/Pods/Pods.xcodeproj/project.pbxproj
- Sources/Classes/JTAppleCalendarCellViewSource.swift
- Sources/Classes/JTAppleCalendarView.swift
- Sources/Classes/JTAppleDayCell.swift
- Sources/Classes/UserInteractionFunctions.swift
Uses enum JTAppleCalendarViewSource as definition of class or Xib for JTAppleDayCell subview.
As bonus allows register class for DayCell directly with type instead of string
```
calendar.registerCellViewClass(cellClass: CellView.self)
```
---
@patchthecode please take a look, and tell me what are you thinking.
I think this simplifies JTAppleDayCell#setupCellView code. But i really just want to register cells with it's type instead of xib or string name of class.
PS: I sucks on naming things so please rename anything to your liking.
> Allows use type of cellView directly

- Sources/Classes/JTAppleCalendarView.swift
It is better to deprecate the value rather than removing it especially on a minor uptake 4.0.2 to 4.0.3 as it will break the build on code using that value.
> Deprecating numberOfRowsPerMonth instead of removing it so it will generate a build warning instead of a failure fro those who were using it.

- Sources/Classes/JTAppleCalendarView.swift
- Sources/Classes/JTCalendarProtocols.swift
Better approach is to weakify JTAppleCalendarViewDataSource and
JTAppleCalendarViewDelegate protocols variables because of retain cycle.
> Weakify JTAppleCalendarViewDataSource and JTAppleCalendarViewDelegate.

- .travis.yml
- Example/JTAppleCalendar.xcodeproj/project.pbxproj
- Updated travis.yml to use xcodebuild instead of xctool (Better compatibility with Swift. 
>  osx_image: xcode7.3
env:
- DESTINATION="OS=9.3,name=iPhone 6s" SCHEME="JTAppleCalendar-Example" SDK=iphonesimulator9.3
- Update XCode test to match the SDK of the Example
- Install pod on the fly when using travis CI
> before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- cd Example
- pod install
> Updated .travis.yml

- Example/Podfile
Just remove some deprecated tag in the example Podfile.
> - Fix Cocoapods 1.0+ depreciation

- JTAppleCalendar.xcodeproj/project.pbxproj
I can't see any reason why the project shouldn't target iOS 8.0 rather than iOS 8.4 as it does now.
> Update deployment target to iOS 8.0

- Sources/JTAppleCalendarView.swift
- Sources/UIScrollViewDelegates.swift
- Sources/UserInteractionFunctions.swift
Reverts patchthecode/JTAppleCalendar#162
Oops, this was a mistake! I should be sleeping already, haha.
I thought these functions were declared by you, but they're from the `UIScrollViewDelegate` protocol, of course. So we can't change their names or they won't be called. Sorry for that. 😳
> Revert "Rename UIScrollViewDelegate methods"

- Sources/JTAppleCalendarView.swift
The check should be on the end date, otherwise the calendar does not refresh when only the end date change in a new calendar range.
> Fix Calendar refresh

- Sources/UIScrollViewDelegates.swift
If you scroll the calendar page with the finger without waiting for the full deceleration, the label update only at the very end.
> Fix label updating

- Sources/JTAppleCalendarView.swift
Delayed tasks may have side effects that then retrigger executing delayed tasks again, causing an infinite loop. This change ensures that delayed tasks will only execute once no matter how many times executeDelayedTasks() gets called.
> Immediately clear delayed tasks

- Sources/UIScrollViewDelegates.swift
When using `scrollToDate(...)` or `scrollToHeaderForDate(...)` on a JTAppleCalendarViewCalendar, the initial value of `lastSavedContentOffset` remains 0 even when scroll animation has finished. As a result, the `isScrollingForward` flag within `scrollViewWillEndDragging` of `UIScrollViewDelegate` is being set incorrectly. This results in the calendar view bouncing back to its initial position on the first time the user scrolls to a previous month. It is 100% reproducible. On the next scroll attempt, the user is able to scroll correctly because the `lastSavedContentOffset` has been updated. It is the initial value of `lastSavedContentOffset` that needs to be calculated correctly after programmatic scroll.
> `lastSavedContentOffset` not set on programmatic scroll

- Sources/UserInteractionFunctions.swift
There is a public facing `visibleDates()` func within UserInteractionFunctions which has purpose "Returns the visible dates of the calendar." 
However, the current implementation is using ALL visible elements of the calendar view to build the valid visible dates array - it is not filtering out header views. What this means is that the visible headers in view are also creating a "valid" index path and resulting date in the final returned array. 
For example, if section header for section 1 is visible on screen, then index path [1, 0] will be added to the array along with index path for the first cell in section 1 which is also [1, 0]. The final array will show repeated dates for instances like this. This is just one example of the trouble this bug is creating. visibleElements() should be …
> visibleDates() no longer improperly returning cell headers

- Sources/UICollectionViewDelegates.swift
Hey @patchthecode - thanks for all the help this last week. I think this will represent my last change for the behavior I need... but who knows :)
Within the UserInteractionFunctions.swift, there is a func selectDates(...) which works well. I have used this in a few spots of my project and I've noticed that it also protects against selecting unsupported dates i.e. dates that are outside the start and end months of the calendar. I think this same logic should be applied to the UICollectionViewDelegate method didSelectItemAt for the CalendarView. I've noticed in testing that manual selection does not protect against unsupported date selection - the use case is when you scroll all the way to the end of your calendar and select an outdate. If this is done programmatically the unsupported …
> Cells outside supported months should not be selectable

- Sources/JTAppleCalendarView.swift
This fixes an issue where scrolling to a date that is at the end of the vertically-scrolling calendar caused overshooting.
Reproducing this issue requires the following:
- Vertically-scrolling calendar that has enough content to make it scrollable
- Calendar must use headers
- Using `.centeredVertically` or `.top` for `preferredScrollPosition` when calling `scroll`
- Scrolling to a date that is at the end of the calendar
This example is taken when scrolling to the last date of the calendar with `preferredScrollPosition` set to `.top`.
Before:
After:
> Fixed an issue that caused scroll to overshoot when using headers.

- Sources/JTAppleCalendarView.swift
Hi
This is a tiny fix for the 25th as an inDate not being reloaded when calling reloadDates. The 25th can appear as an inDate on months with 30 days. An example is between June - July 2017 when using Sunday as the first day of the week.
> Include the 25th when matching counterpart dates

- Example/JTAppleCalendar iOS Example/ViewController.swift
- Sources/CalendarEnums.swift
- Sources/JTAppleCalendarView.swift
- Sources/UIScrollViewDelegates.swift
- Sources/UserInteractionFunctions.swift
The idea is to move from `stopAtEachCalendarFrameWidth` to `stopAtEachCalendarFrame` for a much cleaner API
> Rename ScrollingMode to make sense for both horizontal and vertical scroll direction

- Sources/GlobalFunctionsAndExtensions.swift
Hi,
When finding the end of month day, the current implementation uses a generic date formatter that ignores the calendar and uses the device's Calendar as a reference.
Not all calendars are the same. 
To elaborate on the issue, Gregorian calendar alternates between 31 and 30 days in month, while in Persian Calendar (Jalali) the first 6 months are all 31 days, and the following 5 months have 30 days and the last month is 29 (or 30 in a leap year). Now, in the current implementation, the static formatter uses the Device's calendar to decide on the month's number of days, ignoring the fact that the calendar set for the CalendarView might differ from the device's calendar.
This fix sets the record right with the `Calendar`'s extension that gets the range of days in a month.
> Fixed End of month generation for Custom calendars.

- Sources/JTCalendarProtocols.swift
- Sources/UIScrollViewDelegates.swift
I need to know when the calendar is scrolling to make custom stuff in a external view.
I always need this delegate methods usually when I'm using scrollview, for fancy animation graphics for example (fading opacity when a view is scrolling), so it could be useful for others too.
> add scrollViewDidScroll to calendar delegate

- Sources/JTAppleCalendarView.swift
- Sources/UIScrollViewDelegates.swift
The scrollView could end up having all the time a decelerationRate set to `UIScrollViewDecelerationRateFast`.
Here is how to reproduce:
1- Have a calendar with a `scrollingMode` set to `.none`
2- Flick the scrollView so it scrolls fast
3- Stop it with your finger
4- Quickly, flick it again
=> The scrollView now has a decelerationRate equals to `UIScrollViewDecelerationRateFast`.
This PR makes sure to keep to good decelerationRate.
> Removing `cachedDecelerationRate` in scrollViewWillEndDragging method

- Sources/JTAppleCalendarView.swift
When prepare is called in CalendarLayout it would scroll CalendarView by default to contentOffset = 0.
Therefore if I have a CalendarView with a ContentInset != 0 it will initially be scrolled to contentOffset = CGPoint(x: 0, y: 0) instead of being scroll to the start of the CalendarView (UICollectionView) which is at contentOffset = CGPoint(x: -contentInset.left, y: -contentInset.top).
This PR makes CalendarView scrolled by default to the start when prepare is called in CalendarLayout.
> Changing 'retval' default value in firstContentOffset return method

- Sources/InternalActionFunctions.swift
Fix Issue #995 
We used the same implementation as in the other `scrollTo` method.
> Fix Scrolling in Scroll to Header Function with Animation

- Sources/GlobalFunctionsAndExtensions.swift
The Japenese calendar repeats years so
splitting the date by components and then
recreating it from the components will not work.
Instead use the new interval start and end.
> Fix Crash With Japenese Calendar

- Sources/JTAppleCalendar/JTACMonthView.swift
- Sources/JTAppleCalendar/JTACMonthViewProtocols.swift
Hi! Thanks for releasing v8.0🎉
I probably found the cause of memory leak.
`JTACMonthView.calendarDelegate` and `.calendarDataSource` have strong reference.
`JTACYearView` has weak reference.
```
weak open var calendarDelegate: JTACYearViewDelegate?
weak open var calendarDataSource: JTACYearViewDataSource? {
didSet { setupYearViewCalendar() }
}
```
So, I fixed `JTACMonthView` to have weak reference.
> Fix delegate and datasource strong refer

- Sources/JTAppleCalendar/JTACScrollViewDelegates.swift
for [issue#1260](https://github.com/patchthecode/JTAppleCalendar/issues/1260) 
scrollDidEndDecelerating should not be called when decelerate is false.
> callback scrollDidEndDecelerating delegate at right time

- Sources/JTAppleCalendar/CalendarEnums.swift
- Sources/JTAppleCalendar/JTACMonthQueryFunctions.swift
Me and my colleagues made the migration to version 8.0 this week and experienced a crash in our application. We were wondering what the issue could be. It took us a while to figure it out and that's the reason why I add this PR. 
I added an assert and updated the documentation a bit to hopefully help some others to not try to divide by zero. 
We had the following code in our application: 
`calendarView.scrollingMode = .nonStopTo(customInterval: 0, withResistance: 0)`
and it totally worked fine in JTAppleCalendar 7.1.7. 
We changed it to 
`calendarView.scrollingMode = .nonStopTo(customInterval: 1, withResistance: 0)`
in Version 8.0.2 and it now works like before.
> Add Assert to not try to divide by zero

- Sources/JTAppleCalendar/JTACMonthCell.swift
- Sources/JTAppleCalendar/JTACMonthDelegateProtocol.swift
- Sources/JTAppleCalendar/JTACMonthLayoutProtocol.swift
- Sources/JTAppleCalendar/JTACMonthViewProtocols.swift
- Sources/JTAppleCalendar/JTACYearViewProtocols.swift
I was updating my iOS app to be able to run on Xcode 12.5 (beta) and noticed that Apple is now flagging the use of `class` inherited protocols as `deprecated` in favor of inheriting from `AnyObject`. In my iOS app, we flag warnings as errors so now our app won't compile. I wanted to be able to pitch in and help modernize the code so I went ahead and fixed this deprecation here. 
After a little bit of research, I came across this forum Swift.org [post](https://forums.swift.org/t/class-only-protocols-class-vs-anyobject/11507/4) which seems to point to the discussion where this deprecation discussion started.
> Deprecation warning fix for misc protocols from `class` to `AnyObject`

- Sources/JTAppleCalendar/CalendarEnums.swift
- Sources/JTAppleCalendar/CalendarStructs.swift
This PR  is for the issue https://github.com/patchthecode/JTAppleCalendar/issues/1326.
Although not mentioned in this issue, I think there is a demand for `DaysOfWeek` to handle all cases as a collection as well, so  it also conforms to the `CaseIterable` protocol. (In fact, I want to treat all cases of `DaysOfWeek` as a collection  in my project.)
> MonthsOfYear and DaysOfWeek conforming to protocol CaseIterable

- Sources/JTAppleCalendar/JTACMonthView.swift
Remove isRangeSelectionUsed declaration in order to make JTAppleCalendar compatible with Xcode 15.
> Fix Xcode 15 compilation

- JTAppleCalendar.xcodeproj/project.pbxproj
Would it be possible to remove the signing and team on the JTAppleCalendar Xcode project.  This allows for easy manual integration with submodules.
> Updating the project settings to come without any signing.

- Sources/JTAppleCalendar/JTACCollectionMonthViewDelegates.swift
- Sources/JTAppleCalendar/JTACMonthViewProtocols.swift
The problem is while using the JTAppleCalendar Library in tvOS. Focus is going outside the visible cells and forward to the invisible cell in collection view. This delegate will help to manually switch the focus in above mentioned case. We can force the focus to stay in visible collection view cell with the help of above delegate.
> Added focus delegate for tvOS
