Pod/Classes/JTAppleCalendarView.swift
Resolving #27
Basically just uncommented the code ;)
=> Resolved issue where you can't initialize with frame

JTAppleCalendar.podspec, Sources/Classes/JTAppleCalendarView.swift, Sources/Classes/UserInteractionFunctions.swift
completionHandler was not used in scrollToNextSegment/scrollToPreviousSegment,
add completion func to delayedExecutionClosure
=> fix completion on scrollToNextSegment/scrollToPreviousSegment

Sources/Classes/JTAppleCalendarDelegates.swift
Doh, I didn't even notice I was sending the first pull request to another fork. Thanks for all the work on this great project!
=> Fix for JTAppleCalendarDelegate's canDeselectDate

Sources/JTAppleViews.swift
=> marked the view classes as open instead of public

.travis.yml, Example/JTAppleCalendar iOS Example/AnimationClass.swift, Example/JTAppleCalendar iOS Example/AppDelegate.swift, Example/JTAppleCalendar iOS Example/ExampleDateCells/DateCellCreatedWithXIB/CellView.swift, Example/JTAppleCalendar iOS Example/ViewController.swift, JTAppleCalendar.xcodeproj/project.pbxproj, Sources/JTAppleCalendarDelegates.swift, Sources/JTCalendarProtocols.swift, Sources/UserInteractionFunctions.swift, Tests/JTAppleCalendar_iOSTests.swift, Tests/JTAppleCalendar_tvOSTests.swift
Hey there, how are things? 
I came across this problem in my project because my XIB is actually part of another module (not the main bundle). 
So I added methods to allow that (without breaking backward compatibility)
And updated the travis file :)
Regards,
Denis
=> Define Bundle option in case your Xib are not in the main. Swift3

Sources/UserInteractionFunctions.swift
=> fix adding the same indexPath twice when reload dates

Sources/GlobalFunctionsAndExtensions.swift
Due to Xcode 8.1 compilation errors comparing Date with Date!
=> Added comparer functions

Sources/JTAppleCalendarView.swift
I hope this version is of a slightly improved readability + some best practices implemented
=> Code improvement (safe capture list, early exits)

Example/JTAppleCalendar iOS Example/AnimationClass.swift
removing warnings in the AnimationClass.swift file 
for swift 3.1 and xcode 8.3
=> changing M_PI -> .pi and M_PI_2 -> .pi/2

Sources/JTAppleCalendarView.swift
Just noticed that the exact same if statement is nested, seems like a copy paste error.
=> removed duplicated if statement

Sources/JTAppleCalendarLayoutProtocol.swift
- Fixed a protocol requirement in JTAppleCalendarLayoutProtocol to its updated signature. This fixes a compile-time error such as the one referenced in issue #501
=> - Fixed a protocol requirement in JTAppleCalendarLayoutProtocol

Sources/JTAppleCalendarView.swift
=> Fix message on lifecycle attribute

Sources/JTAppleCalendarView.swift
=> retain cycle

Sources/UIScrollViewDelegates.swift
Hello @patchthecode I'm wondering if you can merge this PR so I can cut a build from this branch.
Thanks,
=> Remove print statements

Sources/CalendarEnums.swift
- I just fix spelling of comment in `InDateCellGeneration` 
- `wilil` to `will` 😂
=> fix comment in InDateCellGeneration

Package.swift
We at JamitLabs developed a dependency management system relying on the Swift Package Manager and as we included your framework in one of our projects I had to adjust the Package.swift file a bit. For further reading please check https://github.com/JamitLabs/Accio.
=> Preparations for usage with Accio (https://github.com/JamitLabs/Accio)

Sources/JTAppleCalendarView.swift
This wasn't building for me at the property level, moved to extension level and it builds.
=> Move Available Check

Sources/JTACScrollViewDelegates.swift
Needed to add additional functionality to scrollViewDidEndDecelerating.
=> Changed access level of scrollViewDidEndDecelerating to open

Sources/JTAppleCalendar/JTACMonthQueryFunctions.swift, Sources/JTAppleCalendar/JTACMonthView.swift
Fixes https://github.com/patchthecode/JTAppleCalendar/issues/1096
=> Cell position handling on month boundaries

JTAppleCalendar.xcodeproj/project.pbxproj, JTAppleCalendar.xcodeproj/project.xcworkspace/contents.xcworkspacedata, JTAppleCalendar.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, JTAppleCalendar.xcodeproj/xcshareddata/xcschemes/JTAppleCalendar.xcscheme, Sources/JTAppleCalendar/Info.plist, Sources/JTAppleCalendar/JTAppleCalendar.h
Hello,
This pull request is about issue #1140 and add Carthage support to JTAppleCalendar.
You may have to edit bundle id from JTAppleCalendar.xcodeproj to set the correct informations.
=> Carthage support.

Sources/JTAppleCalendar/JTACMonthQueryFunctions.swift
now we can use cellState.selectedPosition in correct way for RTL languages
=> Resolve SelectedPosition problem for RTL languages

Sources/JTAppleCalendar/CalendarEnums.swift
=> Typos corrected in CalendarEnums.swift

JTAppleCalendar.podspec
Change podspec file so CocoaPods will see the update
=> Updated podspec to 8.0.4

Sources/JTAppleCalendar/PrivacyInfo.xcprivacy
Added privacy manifest file (PrivacyInfo.xcprivacy)
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files#4284009
=> privacy manifest added
